version: '3.8'

services:
  icecast:
    build: .
    container_name: icecast-kh
    environment:
      - ICECAST_SOURCE_PASSWORD=hackme
      - ICECAST_RELAY_PASSWORD=hackme
      - ICECAST_ADMIN_USER=admin
      - ICECAST_ADMIN_PASSWORD=hackme
      - ICECAST_HOSTNAME=localhost
      - ICECAST_LOCATION=Brazil
      - ICECAST_ADMIN_EMAIL=webmaster@localhost
      - ICECAST_CLIENTS=1000
      - ICECAST_SOURCES=100
      - ICECAST_WEB_PORT=8080
      - ICECAST_SOURCE_PORT=9000
    volumes:
      - ./logs:/var/log/icecast-kh
    restart: always
